on: push
jobs: 
    build-node:
        runs-on: ubuntu-latest
        container: node:18.19.1
        steps: 
            - run: node --version 
            - run: npm --version
            - uses: actions/checkout@v3
            - run: npm install 
            - run: node frontend/car_rental_app/src/App.js 
